apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-payment-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-payment-app
  template:
    metadata:
      labels:
        app: go-payment-app
    spec:
      containers:
        - name: go-payment-app
          image: gcr.io/linear-outcome-456809-t1/go-payment-app:v2
          ports:
            - containerPort: 8080
